<?php
/*
 Template Name: Projects Page
*/
get_header(); ?>
<main id="primary" class="site-main">
    <!-- Control Panel -->
    <div class="control-panel">
        <div class="controls-container">
            <!-- View Toggle -->
            <div class="view-toggle">
                <button id="view-a-btn" class="active">Slideshow</button>
                <button id="view-b-btn">Grid</button>
            </div>

            <!-- Filters -->
            <div class="control-panel-title">
                <h2>Projects</h2>
            </div>
            <div class="filters">
                <!-- Service Filters -->
                <div class="filter-group">
                    <div class="filter-dropdown">
                        <button class="dropdown-trigger" id="service-dropdown-trigger">
                            <span class="filter-label">Services Filter</span>
                            <span class="selected-value">All</span>
                            <span class="dropdown-arrow"><svg width="10" height="6" viewBox="0 0 10 6" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M9.6665 1.00007L5.33312 5L0.999839 1" stroke="#58B947" stroke-miterlimit="10" />
                                </svg>
                            </span>
                        </button>
                        <div class="dropdown-menu" id="service-dropdown">
                            <div class="dropdown-item active" data-filter="all" data-type="service">All</div>
                            <div class="dropdown-item" data-filter="residential" data-type="service">Residential</div>
                            <div class="dropdown-item" data-filter="commercial" data-type="service">Commercial</div>
                            <div class="dropdown-item" data-filter="renovation" data-type="service">Renovation</div>
                            <div class="dropdown-item" data-filter="interior" data-type="service">Interior</div>
                        </div>
                    </div>
                </div>

                <!-- Sector Filters -->
                <div class="filter-group">
                    <div class="filter-dropdown">
                        <button class="dropdown-trigger" id="sector-dropdown-trigger">
                            <span class="filter-label">Element Filter</span>
                            <span class="selected-value">All</span>
                            <span class="dropdown-arrow"><svg width="10" height="6" viewBox="0 0 10 6" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M9.6665 1.00007L5.33312 5L0.999839 1" stroke="#58B947" stroke-miterlimit="10" />
                                </svg>
                            </span>
                        </button>
                        <div class="dropdown-menu" id="sector-dropdown">
                            <div class="dropdown-item active" data-filter="all" data-type="sector">All</div>
                            <div class="dropdown-item" data-filter="office" data-type="sector">Office</div>
                            <div class="dropdown-item" data-filter="retail" data-type="sector">Retail</div>
                            <div class="dropdown-item" data-filter="hospitality" data-type="sector">Hospitality</div>
                            <div class="dropdown-item" data-filter="residential" data-type="sector">Residential</div>
                        </div>
                    </div>
                </div>
                <div class="reset-controls">
                    <button id="reset-filters-btn" class="reset-btn">
                        <span>Reset Filters</span>
                    </button>
                </div>
            </div>
        </div>
        <!-- Project List Toggle -->
        <div class="project-list-toggle">
            <button id="project-list-btn" class="list-toggle-btn">
                <span>Project List</span>
                <span class="toggle-arrow">▼</span>
            </button>
        </div>
        <!-- Project List Dropdown -->
        <div class="project-list-dropdown" id="project-list-dropdown">
            <div class="project-list-header">
                <span id="project-count">0 Projects</span>
            </div>
            <div class="project-list-items" id="project-list-items">
                <!-- Project list items will be generated by JavaScript -->
            </div>
        </div>
    </div>
    <!-- Main Content -->
    <div class="main-content">
        <!-- View A - Slideshow -->
        <div class="view-a" id="view-a">
            <div id="control-panel-spacer-a" class="control-panel-spacer"></div>
            <div class="slideshow-container" id="slideshow-container">
                <!-- Slides will be generated by JavaScript -->
            </div>
            <div class="carousel-nav" id="carousel-nav">
                <!-- Carousel thumbs will be generated by JavaScript -->
            </div>
        </div>

        <!-- View B - Grid -->
        <div class="view-b" id="view-b">
            <div id="control-pannel-spacer-b" class="control-panel-spacer"></div>
            <div class="grid-container">
                <div class="projects-grid" id="projects-grid">
                    <!-- Project cards will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>
</main><!-- #main -->

<?php get_footer(); ?>